version: "3"
services:
  mysqldb:
    image: mysql:latest
    ports:
    - 3307:3306
    environment:
    - MYSQL_DATABASE=mydatabase
    - MYSQL_ROOT_PASSWORD=admin
    volumes:
    - /myvolume:/var/lib/mysql
  dockermysql:
    build:
      context: './'
      dockerfile: Dockerfile
    ports:
    - "8090:8090"
    environment:
    - SPRING_DATASOURCE_USERNAME:root
    - SPRING_DATASOURCE_PASSWORD:admin
    depends_on:
    - mysqldb
    restart: on-failure